# Generated by Django 5.2.8 on 2025-11-25 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posts_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_comments', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='PostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('caption', models.TextField(blank=True)),
                ('username', models.CharField(max_length=100)),
                ('suspicious_comments_count', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('suspicion_ratio', models.FloatField(default=0.0)),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_analyses', to='detection.analysissession')),
            ],
            options={
                'ordering': ['-suspicion_ratio'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('probability', models.FloatField()),
                ('detected_patterns', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_comments', to='detection.analysissession')),
            ],
            options={
                'ordering': ['-probability'],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('suspicious_comments_count', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('suspicion_score', models.FloatField(default=0.0)),
                ('detected_patterns', models.JSONField(default=list)),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_behaviors', to='detection.analysissession')),
            ],
            options={
                'ordering': ['-suspicion_score'],
            },
        ),
    ]
